---
- name: install nginx
  yum:
   name: nginx
   state: present

- name: started and enabled nginx 
  service:
   name: nginx
   state: started
   enabled: yes

- name: add service to firewalld
  firewalld:
   service: http
   state: enabled
   permanent: yes
   immediate: yes
...
